In [1]:
import numpy as np
import pandas as pd

Question 1

In [2]:
a=np.array([-1,1]) 
a

array([-1,  1])

In [3]:
b=np.array([1,1]) 
b

array([1, 1])

In [5]:
result_1 = np.dot(a,b)
result_1

0

# Question 2

In [6]:
X=np.array([[1,0,1],[2,2,2]]) 
X

array([[1, 0, 1],
       [2, 2, 2]])

In [7]:
out=X[0:2,2]
out

array([1, 2])

# 4

In [8]:
X=np.array([[1,0],[0,1]])

Y=np.array([[2,2],[2,2]]) 

Z=np.dot(X,Y) 
Z

array([[2, 2],
       [2, 2]])


# Question 5

Example1.txt:

This is line 1

This is line 2

This is line 3

In [29]:
with open("Example2.txt","r") as file1: 

     FileContent=file1.read() 


print(FileContent) 

This is line A
This is line B



In [30]:
with open("Example2.txt","r") as file1: 

     file_stuff=file1.readline() 

file_stuff

'This is line A\n'

In [11]:
with open("Example2.txt","w") as writefile: 

     writefile.write("This is line A\n") 

     writefile.write("This is line B\n")

# 실행했더니 Example2.txt 생김

In [13]:
with open("Example3.txt","w") as file1: 

    file1.write("This is line C\n") 

In [23]:
np = {'name' : ['A', 'B', 'C'],
      'onoff' : ['on', 'off', 'on'],
      'department' : ['inter', 'inter', 'admin']}
df = pd.DataFrame(np)
df

name onoff department
0    A    on      inter
1    B   off      inter
2    C    on      admin

Question 10
In the lab, you learned you could also obtain a series from a dataframe, df. Select the correct way to assign the column with the header Length to a Pandas series to the variable x.

In [24]:
x = df.[['offf']]

SyntaxError: invalid syntax (1311950668.py, line 1)

In [ ]:
x = [df['onoff']]
x

[0     on
 1    off
 2     on
 Name: onoff, dtype: object]

In [ ]:
x = df['onoff']
x

0     on
1    off
2     on
Name: onoff, dtype: object

In [ ]:
x = df[['onoff']]
x

onoff
0    on
1   off
2    on

Your grade: 100%
Your latest: 100%•
Your highest: 100%•
To pass you need at least 70%. We keep your highest score.